# Generated by Django 5.1.3 on 2024-12-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('distance_from_sun', models.FloatField(verbose_name='Расстояние от Солнца (млн км)')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название миссии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата запуска')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='cosmos.planet', verbose_name='Целевая планета')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='cosmos.planet', verbose_name='Планета')),
            ],
        ),
    ]
